name: A workflow for Group 1 CW
on: push

jobs:
  build:
    name: A workflow for Group 1 CW 
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package
      - name: Build Docker Image
        run: docker build -t semimage .
      - name: Run image
        run: docker run --name semcontainer semimage
      - name: view logs
        run: docker logs semcontainer
